spring.application.name=beertap-api
spring.datasource.url=jdbc:h2:mem:beertapdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jackson.property-naming-strategy=SNAKE_CASE
spring.jackson.deserialization.USE_BIG_DECIMAL_FOR_FLOATS=true
